name: Deploy to AWS S3 BUCKET

on:
  push:
    paths:
      - 'aws-zero-to-pro/Day03/**'  
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'  # Adjust to your region

    - name: Sync static files to AWS S3
      run: |
        aws s3 sync . s3://$S3_BUCKET_NAME --acl public-read --follow-symlinks --delete --exclude ".git/*"
      env:
        S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}  # Bucket name stored in GitHub Secrets
      working-directory: aws-zero-to-pro/Day03  # Set working directory to Day03 folder
