name: Upload Website

on:
  push:
    paths:
      - 'aws-zero-to-pro/Day03/**' 
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure AWS Credentials 
      uses: Configure-aws-credentials@v1
    
      with:
        args: --acl public-read --follow-symlinks --delete
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-south-1'   # optional: defaults to us-east-1
    - name: Sync static files to AWS S3
      run: |
        aws s3 sync . s3://$S3_BUCKET_NAME --delete --exclude ".git/*"  # Sync the current directory to S3
