name: Deploy to AWS S3 BUCKET

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Environment Variables
      run: echo "S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET }}"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'

    - name: Sync static files to AWS S3
      run: |
        aws s3 sync aws-zero-to-pro/Day03/ s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read --follow-symlinks --delete --exclude ".git/*"
